Update CSS token per new design system theming capability
AlaskaAirlines/auro-skeleton pull request #24
Opened 2023-11-09 09:13 UTC by fajar-apri-alaska

# Alaska Airlines Pull Request

**Fixes:** #23 

## Summary:

- Update the design tokens to reflect the new theming conventions regarding tokens from the AuroDesignTokens and JetstreamDesignTokens repo.

## Type of change:

Please delete options that are not relevant.

- [x] Revision of an existing capability

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2023-11-09 09:18 UTC, fajar-apri-alaska commented on demo/style.scss
This demo scss file line 138 have something that used a utility mixin from the old @alaskaairux/webcorestylesheets. Currently I'm still keeping the @alaskaairux/webcorestylesheets if it its still acceptable by the Reviewer.

2023-11-09 23:54 UTC, blackfalcon requested changes

2023-11-09 23:54 UTC, blackfalcon commented on demo/style.scss
Yeah, that's fine. This will all be resolved once the repo is updated to support the latest Generator standard.

2023-11-09 23:54 UTC, blackfalcon commented on demo/style.scss
> +@import './../node_modules/@aurodesignsystem/design-tokens/dist/tokens/SCSSVariables.scss';
```suggestion
```

This is a duplicate from line 10.

2023-11-09 23:54 UTC, blackfalcon commented on package.json
> +    "@alaskaairux/webcorestylesheets": "^3.7.3",
```suggestion
```

this is only a dev dependency

2023-11-09 23:54 UTC, blackfalcon commented on src/style.scss
> +@import './../node_modules/@aurodesignsystem/design-tokens/dist/tokens/SCSSVariables.scss';
```suggestion
```

2023-11-16 12:42 UTC, jason-capsule42 approved these changes

2023-11-16 12:42 UTC, merged

2024-01-30 18:13 UTC, blackfalcon commented
:tada: This PR is included in version 2.1.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-skeleton/v/2.1.1)
- [GitHub release](https://github.com/AlaskaAirlines/auro-skeleton/releases/tag/v2.1.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: